version: '2.3'

x-php: &php
  init: true
  depends_on:
    - db
    - redis
    - elasticsearch
    - xray
  image: humanmade/php
  links:
    - "db:db-read-replica"
    - "s3:s3-${COMPOSE_PROJECT_NAME:-default}.s3.localhost"
  volumes:
    - "${VOLUME}:/usr/src/app:delegated"
  environment:
    DB_HOST: db
    DB_READ_REPLICA_HOST: db-read-replica
    DB_PASSWORD: wordpress
    DB_NAME: wordpress
    DB_USER: wordpress
    REDIS_HOST: redis
    REDIS_PORT: 6379
    WP_DEBUG: 1
    WP_DEBUG_DISPLAY: 0
    PAGER: more
    HM_ENV_ARCHITECTURE: 'local-server'
    HM_DEPLOYMENT_REVISION: 'dev'
    ELASTICSEARCH_HOST: elasticsearch.${COMPOSE_PROJECT_NAME:-default}.altis.dev
    ELASTICSEARCH_PORT: 9200
    AWS_XRAY_DAEMON_HOST: xray
    S3_UPLOADS_ENDPOINT: http://s3.localhost:8000/
    S3_UPLOADS_BUCKET: s3-${COMPOSE_PROJECT_NAME:-default}
    S3_UPLOADS_BUCKET_URL: https://s3-${COMPOSE_PROJECT_NAME:-default}.altis.dev
    S3_UPLOADS_KEY: not-needed
    S3_UPLOADS_SECRET: not-needed
    S3_UPLOADS_REGION: not-needed
    TACHYON_URL: https://tachyon-${COMPOSE_PROJECT_NAME:-default}.altis.dev/uploads

services:
  db:
    image: mysql:5.7
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  redis:
    image: redis:3.2-alpine
    ports:
      - '6379'
  php:
    <<: *php
    ports:
      - '9000'
  nginx:
    image: humanmade/nginx
    networks:
      - proxy
      - default
    depends_on:
      - php
    volumes:
      - "${VOLUME}:/usr/src/app:delegated"
    ports:
      - "8080"
    labels:
      - "traefik.port=8080"
      - "traefik.protocol=https"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=HostRegexp:${COMPOSE_PROJECT_NAME:-default}.altis.dev,{subdomain:[a-z.-_]+}.${COMPOSE_PROJECT_NAME:-default}.altis.dev"
  xray:
    image: amazon/aws-xray-daemon
    ports:
      - 2000
    environment:
      AWS_ACCESS_KEY_ID: YOUR_KEY_HERE
      AWS_SECRET_ACCESS_KEY: YOUR_SECRET_HERE
      AWS_REGION: us-east-1
  cavalcade:
    <<: *php
    entrypoint:
      - /usr/local/bin/cavalcade
    user: "nobody:nobody"
  elasticsearch:
    image: altis-elasticsearch:latest
    build: ./elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200"
    networks:
      - proxy
    labels:
      - "traefik.port=9200"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=HostRegexp:elasticsearch.${COMPOSE_PROJECT_NAME:-default}.altis.dev,{subdomain:[a-z.-_]+}.${COMPOSE_PROJECT_NAME:-default}.altis.dev"
  s3:
    image: fingershock/fakes3
    volumes:
      - "s3:/fakes3_data:rw"
    ports:
      - "8000"
    networks:
      - proxy
    labels:
      - "traefik.port=8000"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=HostRegexp:s3-${COMPOSE_PROJECT_NAME:-default}.altis.dev"
  tachyon:
    image: humanmade/tachyon
    ports:
      - "8081:8080"
    networks:
      - proxy
    labels:
      - "traefik.port=8080"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=HostRegexp:tachyon-${COMPOSE_PROJECT_NAME:-default}.altis.dev"
    environment:
      AWS_REGION: not-needed
      AWS_S3_BUCKET: s3-${COMPOSE_PROJECT_NAME:-default}
      AWS_S3_ENDPOINT: http://s3.localhost:8000/
    links:
      - "s3:s3.localhost"

networks:
  default:
  proxy:
    external:
      name: proxy

volumes:
  db-data:
  es-data:
  tmp:
  s3:
