version: '2.3'
services:
  db:
    image: 'mysql:5.7'
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '-u'
        - wordpress
        - '-pwordpress'
      timeout: 5s
      interval: 5s
      retries: 10
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379'
  php:
    init: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      mailhog:
        condition: service_started
    image: 'humanmade/altis-local-server-php:3.2.0'
    links:
      - 'db:db-read-replica'
      - 's3:s3.localhost'
    external_links:
      - 'proxy:dev.altis.dev'
      - 'proxy:pinpoint-dev.altis.dev'
      - 'proxy:cognito-dev.altis.dev'
      - 'proxy:elasticsearch-dev.altis.dev'
      - 'proxy:s3-dev.altis.dev'
    volumes:
      - '/Users/joe/altis/dev:/usr/src/app:delegated'
      - '/Users/joe/altis/dev/packages/local-server/docker/php.ini:/usr/local/etc/php/conf.d/altis.ini'
      - 'socket:/var/run/php-fpm'
    networks:
      - proxy
      - default
    environment:
      HOST_PATH: /Users/joe/altis/dev
      DB_HOST: db
      DB_READ_REPLICA_HOST: db-read-replica
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WP_DEBUG: 1
      WP_DEBUG_DISPLAY: 0
      PAGER: more
      HM_ENV_ARCHITECTURE: local-server
      HM_DEPLOYMENT_REVISION: dev
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      AWS_XRAY_DAEMON_HOST: xray
      S3_UPLOADS_ENDPOINT: 'https://altis.dev/'
      S3_UPLOADS_BUCKET: s3-dev
      S3_UPLOADS_BUCKET_URL: 'https://s3-dev.altis.dev'
      S3_UPLOADS_KEY: admin
      S3_UPLOADS_SECRET: password
      S3_UPLOADS_REGION: us-east-1
      TACHYON_URL: 'https://dev.altis.dev/tachyon'
      PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -t -i -S mailhog:1025'
      ALTIS_ANALYTICS_PINPOINT_ENDPOINT: 'https://pinpoint-dev.altis.dev'
      ALTIS_ANALYTICS_COGNITO_ENDPOINT: 'https://cognito-dev.altis.dev'
      PHP_XDEBUG_ENABLED: null
      PHP_IDE_CONFIG: serverName=dev.altis.dev
  nginx:
    image: 'humanmade/altis-local-server-nginx:3.1.0'
    networks:
      - proxy
      - default
    depends_on:
      - php
    volumes:
      - '/Users/joe/altis/dev:/usr/src/app:delegated'
      - 'socket:/var/run/php-fpm'
    ports:
      - '8080'
    labels:
      - traefik.frontend.priority=1
      - traefik.port=8080
      - traefik.protocol=https
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=HostRegexp:dev.altis.dev,{subdomain:[a-z.-_]+}.dev.altis.dev'
  xray:
    image: 'amazon/aws-xray-daemon:3.0.1'
    ports:
      - '2000'
    environment:
      AWS_ACCESS_KEY_ID: YOUR_KEY_HERE
      AWS_SECRET_ACCESS_KEY: YOUR_SECRET_HERE
      AWS_REGION: us-east-1
  cavalcade:
    entrypoint:
      - /usr/local/bin/cavalcade
    user: 'nobody:nobody'
    restart: on-failure
    init: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      mailhog:
        condition: service_started
    image: 'humanmade/altis-local-server-php:3.2.0'
    links:
      - 'db:db-read-replica'
      - 's3:s3.localhost'
    external_links:
      - 'proxy:dev.altis.dev'
      - 'proxy:pinpoint-dev.altis.dev'
      - 'proxy:cognito-dev.altis.dev'
      - 'proxy:elasticsearch-dev.altis.dev'
      - 'proxy:s3-dev.altis.dev'
    volumes:
      - '/Users/joe/altis/dev:/usr/src/app:delegated'
      - '/Users/joe/altis/dev/packages/local-server/docker/php.ini:/usr/local/etc/php/conf.d/altis.ini'
      - 'socket:/var/run/php-fpm'
    networks:
      - proxy
      - default
    environment:
      HOST_PATH: /Users/joe/altis/dev
      DB_HOST: db
      DB_READ_REPLICA_HOST: db-read-replica
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WP_DEBUG: 1
      WP_DEBUG_DISPLAY: 0
      PAGER: more
      HM_ENV_ARCHITECTURE: local-server
      HM_DEPLOYMENT_REVISION: dev
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      AWS_XRAY_DAEMON_HOST: xray
      S3_UPLOADS_ENDPOINT: 'https://altis.dev/'
      S3_UPLOADS_BUCKET: s3-dev
      S3_UPLOADS_BUCKET_URL: 'https://s3-dev.altis.dev'
      S3_UPLOADS_KEY: admin
      S3_UPLOADS_SECRET: password
      S3_UPLOADS_REGION: us-east-1
      TACHYON_URL: 'https://dev.altis.dev/tachyon'
      PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -t -i -S mailhog:1025'
      ALTIS_ANALYTICS_PINPOINT_ENDPOINT: 'https://pinpoint-dev.altis.dev'
      ALTIS_ANALYTICS_COGNITO_ENDPOINT: 'https://cognito-dev.altis.dev'
      PHP_XDEBUG_ENABLED: null
      PHP_IDE_CONFIG: serverName=dev.altis.dev
  elasticsearch:
    image: 'humanmade/altis-local-server-elasticsearch:3.0.0'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - 'es-data:/usr/share/elasticsearch/data'
      - '/Users/joe/altis/dev/content/uploads/es-packages:/usr/share/elasticsearch/config/packages'
    ports:
      - '9200'
    networks:
      - proxy
      - default
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl --silent --fail localhost:9200/_cluster/health || exit 1'
      interval: 5s
      timeout: 5s
      retries: 25
    labels:
      - traefik.port=9200
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=HostRegexp:elasticsearch-dev.altis.dev'
    environment:
      - http.max_content_length=10mb
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  s3:
    image: 'minio/minio:RELEASE.2020-03-19T21-49-00Z'
    volumes:
      - 's3:/data:rw'
    ports:
      - '9000'
    networks:
      - proxy
      - default
    environment:
      MINIO_DOMAIN: 's3.localhost,altis.dev,s3'
      MINIO_REGION_NAME: us-east-1
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: 'server /data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - traefik.port=9000
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=HostRegexp:s3-dev.altis.dev'
  s3-sync-to-host:
    image: 'minio/mc:RELEASE.2020-03-14T01-23-37Z'
    restart: unless-stopped
    depends_on:
      - s3
    volumes:
      - '/Users/joe/altis/dev/packages/local-server/docker/minio.json:/root/.mc/config.json'
      - '/Users/joe/altis/dev/content/uploads:/content/uploads:delegated'
    links:
      - s3
    entrypoint: '/bin/sh -c " mc mb -p local/s3-dev && mc policy set public local/s3-dev && mc mirror --watch local/s3-dev /content"'
  tachyon:
    image: 'humanmade/tachyon:2.3.2'
    ports:
      - '8080'
    networks:
      - proxy
    labels:
      - traefik.port=8080
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=HostRegexp:dev.altis.dev,{subdomain:[a-z.-_]+}.dev.altis.dev;PathPrefix:/tachyon;ReplacePathRegex:^/tachyon/(.*) /uploads/$$1'
    environment:
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: s3-dev
      AWS_S3_ENDPOINT: 'https://altis.dev/'
    external_links:
      - 'proxy:s3-dev.altis.dev'
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '8025'
      - '1025'
    networks:
      - proxy
      - default
    labels:
      - traefik.port=8025
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=Host:dev.altis.dev;PathPrefix:/mailhog'
    environment:
      MH_UI_WEB_PATH: mailhog
  cognito:
    ports:
      - '3000'
    networks:
      - proxy
      - default
    restart: on-failure
    image: 'humanmade/local-cognito:1.0.0'
    labels:
      - traefik.port=3000
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=Host:cognito-dev.altis.dev'
  pinpoint:
    ports:
      - '3000'
    networks:
      - proxy
      - default
    restart: on-failure
    image: 'humanmade/local-pinpoint:1.2.2'
    labels:
      - traefik.port=3000
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=Host:pinpoint-dev.altis.dev'
    environment:
      INDEX_ROTATION: OneDay
  kibana:
    image: 'blacktop/kibana:6.3'
    networks:
      - proxy
      - default
    ports:
      - '5601'
    labels:
      - traefik.port=5601
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - 'traefik.frontend.rule=Host:dev.altis.dev;PathPrefix:/kibana'
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - '/Users/joe/altis/dev/packages/local-server/docker/kibana.yml:/usr/share/kibana/config/kibana.yml'
networks:
  default: null
  proxy:
    external:
      name: proxy
volumes:
  db-data: null
  es-data: null
  tmp: null
  s3: null
  socket: null
